site_name: Plebeius Garagicus
site_url: https://plebeiusgaragicus.github.io

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Blog & Pages:
    - About: about.md
  - Static Sites & Tools:
    - Bitcoin Price: bitcoin-price.html
