site_name: Plebeius Garagicus
site_url: https://plebeiusgaragicus.github.io

theme:
  name: readthedocs
  prev_next_buttons_location: none
  include_homepage_in_sidebar: true
  navigation_depth: 4

plugins:
  - search
  - awesome-pages

nav:
  - Home: index.md
  - Posts: posts/
  - PlebTools:
    - Bitcoin Price: bitcoin-price.html
    - NIP-33 Demo: nip33-demo.html
