site_name: Plebeius Garagicus
site_url: https://plebeiusgaragicus.github.io
site_author: Plebeius Garagicus
site_description: A collection of thoughts and ideas

theme:
  name: readthedocs

plugins:
  - search
  - blog:
      blog_dir: blog
      post_date_format: medium
      post_url_format: "{slug}"
      authors: false

markdown_extensions:
  - tables
  - fenced_code

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - About: about.md
